# Week 1: Introduction



August 31-06, 2026

## 📖 Reading

- [ ] (for Mon) [Syllabus](../syllabus.pdf){target="_blank"}
- [ ] (for Wed) [IDS 1 Ch 6 - Importing Data](https://rafalab.dfci.harvard.edu/dsbook-part-1/R/importing-data.html){target="_blank"}
- [ ] (for Fri) [IDS 1 Ch 2 - R Basics](https://rafalab.dfci.harvard.edu/dsbook-part-1/R/R-basics.html){target="_blank"}
- Additional reading: [SC Ch 7 - Introduction to Programming](https://srvanderplas.github.io/stat-computing-r-python/part-gen-prog/00-intro.html){target="_blank"} (this is just designed to help you get into the mindset)


## 📐 Prepare for class

- Print out and bring [cheat sheets](../files/cheat-sheets-combined.pdf){target="_blank"} for R
- [ ] (for Mon) [1.1.p Syllabus Overview](https://usu.instructure.com/courses/819584/assignments/5290598){target="_blank"}
- [ ] (for Wed) [1.2.p Reading Check: Importing Data (IDS Ch 6)](https://usu.instructure.com/courses/819584/assignments/5290579){target="_blank"}
- [ ] (for Wed) [1.2.p Install R](https://usu.instructure.com/courses/819584/assignments/5290555){target="_blank"}
- [ ] (for Fri) [1.3.p Reading Check: R Basics (IDS Ch 2)](https://usu.instructure.com/courses/819584/quizzes/1489305){target="_blank"}


## 🥱 Monday 🌛

- [ ] [Attendence Quiz 08/31](https://usu.instructure.com/courses/819584/quizzes/1463212){target="_blank"}
- [Discussion: Syllabus](../slides/01-syllabus.qmd){target="_blank"}
- [Course Introduction and Motivation](../slides/01-intro.qmd){target="_blank"}
- [ ] [Syllabus Quiz](https://usu.instructure.com/courses/819584/assignments/5290551){target="_blank"}


## 🐪️ Wednesday 🐦‍⬛ 

- [ ] [Attendence Quiz 09/2](https://usu.instructure.com/courses/819584/quizzes/1463708){target="_blank"}
- [Organizing Data](../slides/02-data.qmd)
- [ ] [1.2.p Introduction to Data Science](https://usu.instructure.com/courses/819584/assignments/5290558){target="_blank"} (Individual + In Class)


## 🎉 Friday 🥳

- [ ] [Attendence Quiz 09/4](https://usu.instructure.com/courses/819584/quizzes/1463709){target="_blank"}
- [Intro to Programming](../slides/03-prog-intro.qmd){target="_blank"}
- Programming a Sandwich. [html](../lab/03-programming-sandwich.qmd){target="_blank"},  [qmd template](../lab/_03-programming-sandwich.qmd){target="_blank"} 
- [ ] [Getting to Know You Assignment](https://usu.instructure.com/courses/819584/quizzes/1462883){target="_blank"}


## Extra Resources/Reading

- [R cheat sheets](../demos/r-cheat-sheets.pdf){target="_blank"} - handout from class, but you can reprint them if you lose yours, or keep a digital copy on a tablet if you prefer.
- [Hadley Wickham: Spreadsheets, bikes, and the accidental empire of R packages](https://www.youtube.com/watch?v=KxRnZTl2HVY){target="_blank"} (YouTube, The Test Set) - Hadley Wickham developed many of the R packages we'll use in this course. Hear the back-story as to how he got started!
- [The Jevons Paradox](https://www.youtube.com/watch?v=a6sYYrLTOjQ){target="_blank"} (YouTube, Hank Green) - Why AI (and statistics) do not generate new information.

