# Week 6: Dates, Times, and Distributions



October 05-11, 2026

## 📖 Reading

- [ ] (for Mon) [IDS I Ch 13 - Dates and Times](https://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/dates-and-times.html){target="_blank"}
- [ ] (for Wed) [IDS I Ch 7 - Visualizing Data Distributions](https://rafalab.dfci.harvard.edu/dsbook-part-1/dataviz/distributions.html){target="_blank"}


## 📐 Prepare for class

- [ ] (for Mon) [Reading Check 6.1.p - Dates and Times](https://usu.instructure.com/courses/819584/modules/items/7946533){target="_blank"}  
- [ ] (for Wed) [Reading Check 6.2.p - Visualizing Distributions](https://usu.instructure.com/courses/819584/modules/items/7666801){target="_blank"}
- [ ] [Homework 1](https://usu.instructure.com/courses/819584/assignments/5290611){target="_blank"} [qmd template](../homework/_homework01.qmd){target="_blank"} [html](../homework/homework01.qmd){target="_blank"}


## 🥱 Monday 🌛

- [Attendance Quiz 10/05](https://usu.instructure.com/courses/819584/assignments/5292944){target="_blank"}
- [Dates and Times](../slides/16-dates-times.qmd){target="_blank"}
- [Activity: Dates and Times](https://usu.instructure.com/courses/819584/quizzes/1502123){target="_blank"} [quarto](../lab/_16-lubridate.qmd) [html](../lab/16-lubridate.qmd){target="_blank"}
- Extra Practice: Covid Time Series [quarto](../lab/_16-covid-time-series.qmd){target="_blank"} [html](../lab/16-covid-time-series.qmd) [solutions](../lab/16-covid-time-series-sol.qmd){target="_blank"}


## 🐪️ Wednesday 🐦‍⬛ 

- [Attendance Quiz 10/07](https://usu.instructure.com/courses/819584/assignments/5292945){target="_blank"}
- [Demo: Visualizing Data Distributions](../demos/17-visualizing-distributions.qmd){target="_blank"}
- [Visualizing Data Distributions](../slides/17-vis-dist.qmd){target="_blank"}


## 🎉 Friday 🥳

- Fall Break


## Extra Resources/Reading

- [SC Ch 27 - Dates and Times](https://srvanderplas.github.io/stat-computing-r-python/part-wrangling/07-datetime.html){target="_blank"}
- [IDS I Ch 14 - Locales](https://rafalab.dfci.harvard.edu/dsbook-part-1/wrangling/locales.html){target="_blank"}

