# Week 7: Data Visualization



October 12-18, 2026

## 📖 Reading

- [ ] (for Mon) [IDS I Ch 8 - ggplot2](https://rafalab.dfci.harvard.edu/dsbook-part-1/dataviz/ggplot2.html){target="_blank"}    
[Explanation of ggplot2 syntax and structure](../demos/19-ggplot2.qmd)
- [ ] (for Wed) [IDS I Ch 10 - Data Visualization in Practice](https://rafalab.dfci.harvard.edu/dsbook-part-1/dataviz/dataviz-in-practice.html){target="_blank"}
- [ ] (for Fri) [IDS I Ch 9 - Data Visualization Principles](https://rafalab.dfci.harvard.edu/dsbook-part-1/dataviz/dataviz-principles.html){target="_blank"}


## 📐 Prepare for class

- [ ] (for Mon) Reading Check 7.1
- [ ] (for Wed) Reading Check 7.2
- [ ] (for Fri) Reading Check 7.3


## 🥱 Monday 🌛

- [Attendance Quiz 10/12](https://usu.instructure.com/courses/819584/assignments/5292946){target="_blank"}
- [Data Visualization with `ggplot2`](../slides/19-ggplot2.qmd){target="_blank"}
- [Activity 7.1.p - Introduction to `ggplot2`](https://usu.instructure.com/courses/819584/quizzes/1462912){target="_blank"} [qmd template](../lab/_19-ggplot2.qmd) [html](../lab/19-ggplot2.qmd)


## 🐪️ Wednesday 🐦‍⬛ 

- [Attendance Quiz 10/14](https://usu.instructure.com/courses/819584/assignments/5292947){target="_blank"}
- [Data Visualization in Practice/Advanced `ggplot2`](../slides/20-adv-ggplot2.qmd){target="_blank"}
- [Activity 7.2.p - Advanced `ggplot2`](https://usu.instructure.com/courses/819584/quizzes/1462843) [qmd template](../lab/_20-ggplot2-adv.qmd), [html](../lab/20-ggplot2-adv.qmd), [solutions](../lab/20-ggplot2-adv-sol.qmd)


## 🎉 Friday 🥳

- [Attendance Quiz 10/16](https://usu.instructure.com/courses/819584/assignments/5292962){target="_blank"}
- [Data Visualization Principles](../slides/21-data-vis-principles.qmd){target="_blank"}
- [Lab: Effective Data Visualization](../lab/21-effective-data-vis.qmd){target="_blank"}


## Extra Resources/Reading

This is my research area, so here's an info-dump from my textbook. 
I'm happy to discuss data visualization at any point in office hours! 

  - [SC Ch 18 - Data Visualization Basics](https://srvanderplas.github.io/stat-computing-r-python/part-wrangling/02-basic-data-vis.html){target="_blank"}
  - [SC Ch 19 - Exploratory Data Analysis](https://srvanderplas.github.io/stat-computing-r-python/part-wrangling/02a-eda.html){target="_blank"}
  - [SC Ch 20 - A Grammar of Graphics](https://srvanderplas.github.io/stat-computing-r-python/part-wrangling/02b-graphics.html){target="_blank"}
  - [SC Ch 21 - Creating Good Charts](https://srvanderplas.github.io/stat-computing-r-python/part-wrangling/02c-good-graphics.html){target="_blank"}
  

