---
title: "Submission Checklist"
format:
  html:
    embed-resources: true
---
Use this checklist to ensure you are ready to submit the various stages of the Stat 1080 project.

# Submission Checklist

- [ ] Check your quarto file name -- is it of the form `lastname_firstname_project.qmd`?

- [ ] Check the author (specified around line 3 of the quarto file) -- is your name there?

- [ ] Check that your data file is contained in the `./data/` subfolder of this project. 

- [ ] Render your file using the blue arrow at the top of the RStudio text editor window.
    - [ ] If your file does not render, address any errors in the code leading to failure.
    
- [ ] Preview your rendered file in a browser. Do all of your answers and plots show up the way you expected them to?    
If the answers do not show up the way you want them, check your markdown formatting against the cheat sheet in RStudio (Help -> Cheat Sheets -> Rmarkdown cheat sheets)

- [ ] Run the `lintr` style checks (Canvas -> Course homepage -> Style Guides link under USU picture)
    - [ ] Switch to source mode in RStudio
    - [ ] Addins -> Style active file
    - [ ] Addins -> Lint current file
    - [ ] Address any issues that the lint command raises

- [ ] Render your file again, to check that the `styler` and `lintr` addons didn't mess up any formatting. 

- [ ] (Project Visualizations assignment only) Upload your rendered HTML file (named `lastname_firstname_project.html`) to Canvas.

- [ ] (Project Submissions assignments) Zip all of the files in the project folder (e.g. including ./data, this qmd file, and any rendered HTML files) together into a zip file named `lastname_firstname_project.zip`

- [ ] Double-check your submission - is the file you uploaded the one you want to be graded?